### ISSUE TITLE
是否去除 React 严格模式

### ISSUE THREAD

**Issue by okcodycom** [anandzhang/issue-feedback-react#5]
`create-react-app` 脚手架创建 `React` 项目后，自动使用了 `StrictMode` 严格模式：

https://github.com/anandzhang/issue-feedback-react/blob/3f38478f9631b235df7a73b51f8c8304b2dc7bab/app/src/index.js#L7-L12

但是项目使用了 `antd 4.2.2` 出现很多与 `antd` 组件有关的报错。

**Comment by okcodycom** [comment]
`Menu` 组件：

https://github.com/anandzhang/issue-feedback-react/blob/3f38478f9631b235df7a73b51f8c8304b2dc7bab/app/src/components/Header/index.jsx#L20-L23

**报错：**

```
Warning: 
  findDOMNode is deprecated in StrictMode.
  findDOMNode was passed an instance of DOMWrap which is inside StrictMode.
  Instead, add a ref directly to the element you want to reference.
```

---

`Button` 组件：

https://github.com/anandzhang/issue-feedback-react/blob/3f38478f9631b235df7a73b51f8c8304b2dc7bab/app/src/components/FeedbackList/index.jsx#L61

报错同 `Menu` 组件

---

`List` 组件：

https://github.com/anandzhang/issue-feedback-react/blob/3f38478f9631b235df7a73b51f8c8304b2dc7bab/app/src/components/FeedbackList/index.jsx#L66

**报错：**

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
```

**Comment by anandzhang** [comment]
使用 `antd` 的 `Button` 组件，同 `Menu` 一样的错误。

**Comment by okcodycom** [comment]
查找到 `antd` 的 issue：https://github.com/ant-design/ant-design/issues/22493 。

> https://github.com/ant-design/ant-design/issues/22493#issuecomment-605497219
Removing strict mode just for the sake of a button is ridiculous. This is a legit problem with antd that needs to be fixed.

我也觉得是这个道理。

**Comment by onekx** [comment]
> 查找到 `antd` 的 issue：[ant-design/ant-design#22493](https://github.com/ant-design/ant-design/issues/22493) 。
> 
> > [ant-design/ant-design#22493 (comment)](https://github.com/ant-design/ant-design/issues/22493#issuecomment-605497219)
> > Removing strict mode just for the sake of a button is ridiculous. This is a legit problem with antd that needs to be fixed.
> 
> 我也觉得是这个道理。

赞同
